### ISSUE TITLE
How to make nix load before vscode extension

### ISSUE THREAD

**Issue by Rizary** [xtruder/nix-devcontainer#6]
I have some problem where my extensions cannot detect nix-develop or nix-shell, even if I use nix-shell vscode extension.

**Comment by offlinehacker** [comment]
There was a bug related to direnv volume mount path, as direnv has changed default config path. This is what is most likely causing issues. I have updated template and examples, look into this commit for details: https://github.com/xtruder/debian-nix-devcontainer/commit/7e0afa46676fe22334c1bb4e820edaf4228589ff

**Comment by Rizary** [comment]
@offlinehacker Thank you, I have changed it and after run `direnv allow` my extensions seems detecting the profile. 

Although I have an error: https://github.com/haskell/haskell-language-server/issues/2213, but other extension is fine.

**Comment by offlinehacker** [comment]
I have updated this project to use `arrterian.nix-env-selector` for initial load of nix environment, instead of building it while using vscode environment probe. This is mainly, because old setup does not work reliably anymore, as vscode environment probe times out after 10 seconds. I have also updated bunch of other stuff and updated README.

The new setup also kind of is a more proper and more simplified way to load environment, as it does not have any hacks to detect whether vscode is running environment probe. Please be aware that image was renamed to **xtruder/nix-devcontainer**, so old image stay, as it is, but it hasn't been updated for a long time.

I am closing this issue, as this should be fixed now.
